### PR TITLE
egl-wayland: Send explicit sync points before attaching a surface

### PR DESCRIPTION
**Pull request by amshafer**
Currently we call `wl_surface_attach`, then `send_explicit_sync_points`. This can theoretically cause issues due to `send_explicit_sync_points` exiting due to an error, causing `wlEglSendDamageEvent` to exit without finishing the surface commit. Not only is `wl_surface_commit` never called, but we are missing explicit sync points from the commit which is a protocol error.

This change switches the order, calling `send_explicit_sync_points` first. This is valid because the `linux_drm_syncobj_v1` protocol applies the acquire/release points to the attached buffer at commit time.

This affects at least some of the crashes seen in #110, #117  and #118

### CODE REVIEW

**Comment by amshafer** [comment]
CC: @mahkoh for pointing this out (thanks!)

**Review by cubanismo — APPROVED** [review]

**Comment by furegulo** [comment]
I installed this patch on my Arch-based CachyOS system, with Nvidia 4070ti Super. I'm still getting a few random crashes with Firefox-based browsers with error message 

> cachyos-x8664 cachy-browser[12103]: Exiting due to channel error. 

Though this seems a lot more stable than the previous egl-wayland, which Arch reverted to the older one.

**Comment by VictorR2007** [comment]
> I'm still getting a few random crashes with Firefox-based browsers with error message

Firefox Nightly is actively fixing such errors. With each update, Firefox Nightly reduces the number of Firefox crashes.

**Comment by entailz** [comment]
Still crashing here for me as well on all branches of Firefox including Dev and Nightly, although like VictorR2007 said above, the crashes are less frequent.
```
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#74: error 5: Missing timeline
 (t=3.34461) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#74: error 5: Missing timeline

Gdk-Message: 11:29:39.714: Error 71 (Protocol error) dispatching to Wayland display.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=1.65293) Exiting due to channel error.
```

**Comment by amshafer** [comment]
@entailz Can you please include a log of that crash with `WAYLAND_DEBUG=1`? Also would be helpful to know what compositor.

**Comment by entailz** [comment]
I'm on Hyprland with explicit sync enabled, here's a log from Firefox ESR
[logs.txt](https://github.com/user-attachments/files/16499604/logs.txt)

**Comment by entailz** [comment]
I just tested this commit on 560.28.03 with explicit sync enabled and I'm still getting the same crash in Firefox 
```
 Wayland protocol error: wp_linux_drm_syncobj_surface_v1#72: error 5: Missing timeline
```

**Comment by amshafer** [comment]
You might want to check with the Hyprland devs if you haven't already, from your log it looks like the correct commit sequences are happening but according to the new Hyprland linux-drm-syncobj implementation the release timeline/point was not specified. It might be worth seeing if they find anything obviously wrong with their timeline tracking, just to verify.

I'm also looking into a potential issue with egl-wayland's event queue usage. There's a chance it could be causing what you see but I haven't reproduced your crash myself so it's hard to say. I'll get back to you about testing that since you have a more consistent repro for some reason.

**Comment by entailz** [comment]
Okay, will do. Thanks for taking a look at the logs. I was told it could potentially be a Firefox issue, does that sound right? It seems to happen less on firefox nightly.

**Comment by vaxerski** [comment]
hi! hyprland dev here. This is an nvidia bug, this didn't fix this one edge case :(

took me a while to spot this one, but:

20240805_23h42m06s

**Comment by mahkoh** [comment]
If at commit time a syncobj_surface exists, then the content update must contain acquire and release points if and only if it attaches a non-null buffer.

**Comment by vaxerski** [comment]
@entailz I've moved the check back after the buffer check in https://github.com/hyprwm/Hyprland/pull/7151/commits/b0437c9f76dc3533eed23f5a9aec186d4a32f4d3

If I am reading right, this now should error out with `WP_LINUX_DRM_SYNCOBJ_SURFACE_V1_ERROR_NO_BUFFER` because timeline 61 is attached while there is no buffer

**Comment by mahkoh** [comment]
>ah, right, my bad, buffer 65 is destroyed. You're right

The buffer being destroyed is irrelevant. Destroying a buffer has no effect on surfaces it is attached to.

>Though... 61 is still attached and the buffer is gone... so that's still wrong no?

The commit your last arrow points to does not interact with the syncobj protocol at all because it does not attach a buffer. Its only contents are a frame request.

**Comment by vaxerski** [comment]
makes sense I guess, thanks!

**Comment by entailz** [comment]
@vaxerski working now, no crashes! thanks both of you for your patience.

**Pull request merged**
